{
  inputs,
  pkgs,
  lib,
  ...
}:

{
  # Runtime
  virtualisation = {
    docker = {
      enable = true;
      autoPrune.enable = true;
    };
    oci-containers = {
      backend = "docker";

      # Containers
      containers = {
        "bookorbit-db" = {
          image = "pgvector/pgvector:pg16@sha256:7d400e340efb42f4d8c9c12c6427adb253f726881a9985d2a471bf0eed824dff";
          environment = {
            "PGDATA" = "/var/lib/postgresql/data/pgdata";
            "POSTGRES_DB" = "bookorbit";
            "POSTGRES_PASSWORD" = inputs.secrets.postgres_password;
            "POSTGRES_USER" = "bookorbit";
          };
          volumes = [ "/home/luca/Downloads/data/postgres:/var/lib/postgresql/data:rw" ];
          log-driver = "journald";
          extraOptions = [
            ''--health-cmd=pg_isready -U "''${POSTGRES_USER}" -d "''${POSTGRES_DB}"''
            "--health-interval=10s"
            "--health-retries=10"
            "--health-start-period=20s"
            "--health-timeout=5s"
            "--network-alias=postgres"
            "--network=bookorbit_default"
          ];
        };
        "bookorbit-app" = {
          image = "ghcr.io/bookorbit/bookorbit:sha-54e228eb2a79";
          environment = {
            "APP_IMAGE" = "ghcr.io/bookorbit/bookorbit:sha-54e228eb2a79";
            "APP_PORT" = "3000";
            "APP_URL" = "https://bookorbit.lucaantonelli.xyz";
            "BOOKS_HOST_PATH" = "./books";
            "BOOK_DOCK_PATH" = "";
            "CLIENT_URL" = "https://bookorbit.lucaantonelli.xyz";
            "DATABASE_URL" = "";
            "JWT_SECRET" = inputs.secrets.jwt_token;
            "NODE_ENV" = "production";
            "NODE_MAX_OLD_SPACE_SIZE" = "2048";
            "PGID" = "1000";
            "PORT" = "3000";
            "POSTGRES_DB" = "bookorbit";
            "POSTGRES_HOST" = "postgres";
            "POSTGRES_PASSWORD" = inputs.secrets.postgres_password;
            "POSTGRES_PORT" = "5432";
            "POSTGRES_USER" = "bookorbit";
            "PUID" = "1000";
            "SETUP_BOOTSTRAP_TOKEN" = inputs.secrets.bootstrap_token;
          };
          volumes = [
            "/home/luca/Downloads/books:/books:rw"
            "/home/luca/Downloads/data/app:/data:rw"
          ];
          ports = [ "3000:3000/tcp" ];
          dependsOn = [ "bookorbit-db" ];
          log-driver = "journald";
          extraOptions = [
            "--cap-add=CHOWN"
            "--cap-add=DAC_OVERRIDE"
            "--cap-add=FOWNER"
            "--cap-add=SETGID"
            "--cap-add=SETUID"
            "--cap-drop=ALL"
            ''--health-cmd=["node", "-e", "const p=process.env.PORT||3000;fetch('http://127.0.0.1:'+p+'/api/v1/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]''
            "--health-interval=30s"
            "--health-retries=3"
            "--health-start-period=20s"
            "--health-timeout=5s"
            "--network-alias=app"
            "--network=bookorbit_default"
            "--security-opt=no-new-privileges:true"
          ];
        };
      };
    };

  };
  systemd = {
    services = {
      "docker-bookorbit-app" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
          RestartMaxDelaySec = lib.mkOverride 90 "1m";
          RestartSec = lib.mkOverride 90 "100ms";
          RestartSteps = lib.mkOverride 90 9;
        };
        after = [ "docker-network-bookorbit_default.service" ];
        requires = [ "docker-network-bookorbit_default.service" ];
        partOf = [ "docker-compose-bookorbit-root.target" ];
        wantedBy = [ "docker-compose-bookorbit-root.target" ];
      };
      "docker-bookorbit-db" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
          RestartMaxDelaySec = lib.mkOverride 90 "1m";
          RestartSec = lib.mkOverride 90 "100ms";
          RestartSteps = lib.mkOverride 90 9;
        };
        after = [ "docker-network-bookorbit_default.service" ];
        requires = [ "docker-network-bookorbit_default.service" ];
        partOf = [ "docker-compose-bookorbit-root.target" ];
        wantedBy = [ "docker-compose-bookorbit-root.target" ];
      };
      "docker-network-bookorbit_default" = {
        path = [ pkgs.docker ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "docker network rm -f bookorbit_default";
        };
        script = ''
          docker network inspect bookorbit_default || docker network create bookorbit_default
        '';
        partOf = [ "docker-compose-bookorbit-root.target" ];
        wantedBy = [ "docker-compose-bookorbit-root.target" ];
      };
    };
    targets = {
      "docker-compose-bookorbit-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };
  };
}
