# Auto-generated by compose2nix.

{ inputs, pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable then "podman+" else "podman*";
  in { "${matchAll}".allowedUDPPorts = [ 53 ]; };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."bookorbit-app" = {
    image = "ghcr.io/bookorbit/bookorbit:latest";
    environment = {
      "APP_IMAGE" = "ghcr.io/bookorbit/bookorbit:latest";
      "APP_PORT" = "3000";
      "APP_URL" = "https://bookorbit.lucaantonelli.xyz";
      "BOOKS_HOST_PATH" = "./books";
      "BOOK_DOCK_PATH" = "";
      "CLIENT_URL" = "https://bookorbit.lucaantonelli.xyz";
      "DATABASE_URL" = "";
      "JWT_SECRET" = inputs.secrets.bookorbit.jwt_token;
      "NODE_ENV" = "production";
      "NODE_MAX_OLD_SPACE_SIZE" = "2048";
      "PGID" = "1000";
      "PORT" = "3000";
      "POSTGRES_DB" = "bookorbit";
      "POSTGRES_HOST" = "postgres";
      "POSTGRES_PASSWORD" = inputs.secrets.bookorbit.postgres_password;
      "POSTGRES_PORT" = "5432";
      "POSTGRES_USER" = "bookorbit";
      "PUID" = "1000";
      "SETUP_BOOTSTRAP_TOKEN" = inputs.secrets.bookorbit.bootstrap_token;
    };
    volumes = [
      "/home/luca/Downloads/books:/books:rw"
      "/home/luca/Downloads/data/app:/data:rw"
    ];
    ports = [ "3000:3000/tcp" ];
    dependsOn = [ "bookorbit-db" ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=CHOWN"
      "--cap-add=DAC_OVERRIDE"
      "--cap-add=FOWNER"
      "--cap-add=SETGID"
      "--cap-add=SETUID"
      "--cap-drop=ALL"
      ''
        --health-cmd=["node", "-e", "const p=process.env.PORT||3000;fetch('http://127.0.0.1:'+p+'/api/v1/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]''
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=20s"
      "--health-timeout=5s"
      "--network-alias=app"
      "--network=bookorbit_default"
      "--security-opt=no-new-privileges:true"
    ];
  };
  systemd.services."podman-bookorbit-app" = {
    serviceConfig = { Restart = lib.mkOverride 90 "always"; };
    after = [ "podman-network-bookorbit_default.service" ];
    requires = [ "podman-network-bookorbit_default.service" ];
    partOf = [ "podman-compose-bookorbit-root.target" ];
    wantedBy = [ "podman-compose-bookorbit-root.target" ];
  };
  virtualisation.oci-containers.containers."bookorbit-db" = {
    image =
      "pgvector/pgvector:pg16@sha256:7d400e340efb42f4d8c9c12c6427adb253f726881a9985d2a471bf0eed824dff";
    environment = {
      "PGDATA" = "/var/lib/postgresql/data/pgdata";
      "POSTGRES_DB" = "bookorbit";
      "POSTGRES_PASSWORD" = inputs.secrets.bookorbit.postgres_password;
      "POSTGRES_USER" = "bookorbit";
    };
    volumes =
      [ "/home/luca/Downloads/data/postgres:/var/lib/postgresql/data:rw" ];
    log-driver = "journald";
    extraOptions = [
      ''--health-cmd=pg_isready -U "''${POSTGRES_USER}" -d "''${POSTGRES_DB}"''
      "--health-interval=10s"
      "--health-retries=10"
      "--health-start-period=20s"
      "--health-timeout=5s"
      "--network-alias=postgres"
      "--network=bookorbit_default"
    ];
  };
  systemd.services."podman-bookorbit-db" = {
    serviceConfig = { Restart = lib.mkOverride 90 "always"; };
    after = [ "podman-network-bookorbit_default.service" ];
    requires = [ "podman-network-bookorbit_default.service" ];
    partOf = [ "podman-compose-bookorbit-root.target" ];
    wantedBy = [ "podman-compose-bookorbit-root.target" ];
  };

  # Networks
  systemd.services."podman-network-bookorbit_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f bookorbit_default";
    };
    script = ''
      podman network inspect bookorbit_default || podman network create bookorbit_default
    '';
    partOf = [ "podman-compose-bookorbit-root.target" ];
    wantedBy = [ "podman-compose-bookorbit-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-bookorbit-root" = {
    unitConfig = { Description = "Root target generated by compose2nix."; };
    wantedBy = [ "multi-user.target" ];
  };
}
