{
  config,
  inputs,
  lib,
  ...
}:
let
  fireflyHost = "firefly.${inputs.secrets.domain}";
  importerHost = "firefly-import.${inputs.secrets.domain}";

  httpsFastcgi = socket: {
    fastcgiParams = {
      SCRIPT_FILENAME = "$request_filename";

      # Cloudflare terminates TLS; cloudflared -> nginx is HTTP.
      # Tell PHP about the externally visible scheme.
      REQUEST_SCHEME = "https";
      HTTPS = "on";
    };

    # Replace the FastCGI block generated by the Firefly modules,
    # because it includes nginx's normal fastcgi_params which would
    # set REQUEST_SCHEME=$scheme again.
    extraConfig = lib.mkForce ''
      fastcgi_param modHeadersAvailable true;
      fastcgi_pass unix:${socket};
    '';
  };
in
{
  services.firefly-iii = {
    enable = true;
    enableNginx = true;
    virtualHost = fireflyHost;

    settings = {
      TZ = "Europe/Zurich";

      APP_KEY_FILE = config.sops.secrets.firefly-app-key.path;

      COOKIE_SECURE = true;
    };
  };

  services.firefly-iii-data-importer = {
    enable = true;
    enableNginx = true;
    virtualHost = importerHost;

    settings = {
      FIREFLY_III_URL = "https://${fireflyHost}";

      TZ = "Europe/Zurich";
    };
  };
  services.nginx.virtualHosts.${fireflyHost}.locations."~ \\.php$" =
    httpsFastcgi config.services.phpfpm.pools.firefly-iii.socket;

  services.nginx.virtualHosts.${importerHost}.locations."~ \\.php$" =
    httpsFastcgi config.services.phpfpm.pools.firefly-iii-data-importer.socket;
}
