# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  inputs,
  config,
  ...
}:
let
  storytellerDataDir = "/srv/storyteller";
  inherit (import ./nginx-proxy.nix) cloudflareProxy;
  host = "127.0.0.1";
  port = "8001";
in
{

  virtualisation = {
    docker = {
      enable = true;
      autoPrune.enable = true;
    };
    virtualisation.oci-containers.backend = "docker";

    # Containers
    oci-containers.containers."storyteller-web" = {
      image = "registry.gitlab.com/storyteller-platform/storyteller:latest";
      autoStart = true;
      environment = {
        "STORYTELLER_SECRET_KEY_FILE" = config.sops.secrets.storyteller-secret.path;
      };
      volumes = [
        "${storytellerDataDir}:/data:rw"
      ];
      ports = [
        "${port}:${port}/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=web"
        "--network=storyteller_default"
      ];
    };
  };
  systemd = {
    services = {
      "docker-storyteller-web" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "on-failure";
          RestartSec = lib.mkOverride 90 "10s";
        };
        after = [
          "docker-network-storyteller_default.service"
        ];
        requires = [
          "docker-network-storyteller_default.service"
        ];
        partOf = [
          "docker-compose-storyteller-root.target"
        ];
        wantedBy = [
          "docker-compose-storyteller-root.target"
        ];
      };

      # Networks
      "docker-network-storyteller_default" = {
        path = [ pkgs.docker ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "docker network rm -f storyteller_default";
        };
        script = ''
          docker network inspect storyteller_default || docker network create storyteller_default
        '';
        partOf = [ "docker-compose-storyteller-root.target" ];
        wantedBy = [ "docker-compose-storyteller-root.target" ];
      };
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."docker-compose-storyteller-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };

  services.nginx.virtualHosts."storyteller.${inputs.secrets.domain}" = {
    locations."/" = cloudflareProxy {
      proxyPass = "http://${host}:${port}";
    };
  };
}
